server:
  port: 8081
spring:
  application:
    name: comment
  datasource:
    url: jdbc:mysql://34.134.15.232:3306/comment_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
