server:
  port: 8081
spring:
  application:
    name: comment
  datasource:
    url: jdbc:mysql://mysql:${GATEWAY_HOST}/test_comment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update
