name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Set environment variables
      run: |
        echo "GATEWAY_HOST=34.134.15.232" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Jar build
      run: ./gradlew build
    
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .

    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}


    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          docker rm -f ci-server-comment
          docker run --name ci-server-comment -p 8081:8081 --network ${{ secrets.DOCKER_NETWORK }} -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
